
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hospital.Models
{

using System;
    using System.Collections.Generic;
    
public partial class cita
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cita()
    {

        this.factura = new HashSet<factura>();

    }


    public int idCita { get; set; }

    public Nullable<int> idEmpleado { get; set; }

    public Nullable<int> idPaciente { get; set; }

    public Nullable<System.DateTime> fechaCita { get; set; }



    public virtual empleado empleado { get; set; }

    public virtual paciente paciente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<factura> factura { get; set; }

}

}
