

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hospital.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class hospitalEntities : DbContext
{
    public hospitalEntities()
        : base("name=hospitalEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<cita> cita { get; set; }

    public virtual DbSet<empleado> empleado { get; set; }

    public virtual DbSet<factura> factura { get; set; }

    public virtual DbSet<paciente> paciente { get; set; }

    public virtual DbSet<receta> receta { get; set; }

    public virtual DbSet<visita> visita { get; set; }

}

}

